### ISSUE TITLE
Update for Vaadin 22

### ISSUE THREAD

**Issue by krankkkk** [vaadin-component-factory/vcf-enhanced-dialog#4]
With Vaadin 22 beeing a new LTS, would it be possible to update this to be compatible with Vaadin 22?

Currently it is incompatible because on an import and depending logic on `vaadin-dialog`.
Specifically in vcf-enhanced-dialog.js:8 `import { getMouseOrFirstTouchEvent } from '@vaadin/vaadin-dialog/src/vaadin-dialog-utils';`.

Changing to `@vaadin/dialog/src/vaadin-dialog-utils` seems to fix the incompatibility,

**Comment by stefanuebe** [comment]
The issue here might "simply" be, that the old modules are not referencing all files from the new modules. A simple reference in the old modules (named "vaadin-...") should fix that, too.

**Comment by stefanuebe** [comment]
One workaround is to modifiy the webapp.config.js as following (kiitos and credits to @tomivirkki):

```
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

const mergedConfig = merge(flowDefaults);
mergedConfig.resolve.alias['@vaadin/vaadin-dialog/src/vaadin-dialog-utils'] = '@vaadin/dialog/src/vaadin-dialog-utils.js';
module.exports = mergedConfig;
```
